fix(github): fix cli executable in workflow release.yml
```
ModuleNotFoundError: No module named 'diffusers'
[PYI-31848:ERROR] Failed to execute script 'cli' due to unhandled exception!
```